@startuml
top to bottom direction
skinparam packageStyle rectangle

' External elements
package "External" {
    rectangle GmClient
    rectangle UserClient
    database Database
}

' Infrastructure layer
package "Infrastructure" {
    rectangle HttpGameHandler
    rectangle GameRepository
}

' Application layer
package "Application" {
    rectangle GameHandler
}

' Domain layer
package "Domain" {
    rectangle Game
}

' Flow
GmClient --> HttpGameHandler
UserClient --> HttpGameHandler
HttpGameHandler --> GameHandler
GameHandler --> Game
GameHandler --> GameRepository
GameRepository --> Database
@enduml