@startuml

actor "Client" as Cl
participant "HttpHandler" as Http
participant "UserAuthHandler" as Auth
participant User
participant "JwtGeneratorTrait" as JwtG
participant "JwtValidatorTrait" as JwtV
participant "UserRepositoryTrait" as Repo

note over Cl,Repo: User Registration
Cl -> Http: POST /register
Http -> Auth: register
Auth -> User: new
User --> Auth: User
Auth -> Repo: save
Auth -> JwtG: generate_user_jwt
JwtG --> Auth: Token
Auth --> Http: Token
Http --> Cl: Token

note over Cl,Repo: User Login
Cl -> Http: POST /login
Http -> Auth: login
Auth -> Repo: getById
Repo --> Auth: User
Auth -> JwtG: generate_user_jwt
JwtG --> Auth: Token
Auth --> Http: Token
Http --> Cl: Token

note over Cl,Repo: Request to protected route
Cl -> Http: some route
note over Http: Middleware
Http -> Auth: login
Auth -> JwtG: validate_user_jwt
JwtG -> Repo: getById
Repo --> JwtG: User
JwtG --> Auth: User
Auth --> Http: User
note over Http: Handle Request

@enduml
